import { Roboto } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const roboto = Roboto({
    weight: ["400", "500", "700"],
    style: ["normal", "italic"],
    subsets: ["cyrillic", "latin"],
});

export const metadata = {
    title: "Билетопоиск",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <div className="app-container">
                    <Header />
                    <main className="app-main">{children}</main>
                    <Footer />
                </div>

                <div className="modal-container"></div>
            </body>
        </html>
    );
}
